test_suite.py::MyTestSuite::test_4
--------------------------------------------------------------------
Last Page: https://xkcd.com/1670/
  Browser: chrome
Timestamp: 1629217007  (Unix Timestamp)
     Date: Tuesday, 17 August 2021
     Time: 11:16:47 PM  (SE Asia Standard Time, UTC+07:00)
--------------------------------------------------------------------
Traceback: File "c:\users\dell\appdata\local\programs\python\python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "D:\SeleniumBase\examples\test_suite.py", line 31, in test_4
    self.assert_element("FakeElement.DoesNotExist", timeout=0.5)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\seleniumbase\fixtures\base_case.py", line 7003, in assert_element
    self.wait_for_element_visible(selector, by=by, timeout=timeout)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\seleniumbase\fixtures\base_case.py", line 4837, in wait_for_element_visible
    return page_actions.wait_for_element_visible(
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 339, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 132, in timeout_exception
    raise exception(message)
Exception: Message: 
 Element {FakeElement.DoesNotExist} was not present after 0.5 seconds!
